CC=-gnatmake
FLAGS=-gnatwae

all: bank cards graph vector gfn rgb

bank:
	$(CC) $(FLAGS) bank_accounts.adb

cards:
	$(CC) $(FLAGS) cards.adb

graph:
	$(CC) $(FLAGS) graph.adb

vector:
	$(CC) $(FLAGS) vectors.adb

gfn:
	$(CC) $(FLAGS) gf2n.adb

rgb:
	$(CC) $(FLAGS) rgb.adb

clean:
	-rm *.ali *.o

super_clean:
	-rm *.ali *.o hello_world loops vowels calc box_geometry animals
